### PR TITLE
add ARTIS ERC1056 contract addresses to spec

### PR DESCRIPTION
**Pull request by PeterTheOne**
See:
https://explorer.tau1.artis.network/address/0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B/contracts
https://explorer.sigma1.artis.network/address/0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B/contracts

Is there a way to register `ethr-network` for a network? `artis_t1` and `artis_s1` in this case.

Should there be more changes to ethr-did-resolver?

### CODE REVIEW

**Review by mirceanis — APPROVED** [review]
Thank you for adding these.

At the moment there is no way to register contract deployment on these networks in code.
It is up to the configuration of the ethr-did-resolver to call the correct network.

Here's an example:
https://github.com/uport-project/uport-did-driver/blob/9fdcac0b2c676e6d1484cd7c91164af189586978/expressresolver.js#L10

**Comment by mirceanis** [comment]
Some next steps on this road would be:
* specify the proper names of these private networks in the deployment table here
* add `chainID`s to the table
* add a verification of chainID when the ethr-did-resolver is first called

**Comment by PeterTheOne** [comment]
> * specify the proper names of these private networks in the deployment table here

Where?

Thanks, I'll follow up with these next steps..

**Comment by mirceanis** [comment]
> Where?

Right now there's no other place than the list of deployments. We should turn this list into a table or something.

> Thanks, I'll follow up with these next steps..

This resolver can survive as is for a while, the problem of how to use such a resolver on private networks is still being discussed in DIF since it affects other DID methods too.
It's best to not jump right into implementation since I don't know if the steps I proposed earlier are the correct course of action.

**Pull request merged**
